services:
  user-management:
    build:
      target: ${APP_ENV}
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - db

  user-management-dev:
    extends: user-management
    profiles:
      - dev
    volumes:
      - ./:/app

  db:
    image: postgres:17.4
    ports:
    - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./data:/var/lib/postgresql/data